
set(ENABLED_GEMS
    test-atom-multicam
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    PhysX
    PrimitiveAssets
    PrefabBuilder
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    DiffuseProbeGrid
    Compression
    ImGui
)
